# Generated by Django 4.2.21 on 2026-02-15 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorShade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="مثال: SH-1024",
                        max_length=50,
                        unique=True,
                        verbose_name="کد شید",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام رنگ")),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: #FF5733",
                        max_length=7,
                        verbose_name="کد رنگ HEX",
                    ),
                ),
                (
                    "recipe",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="نسبت مواد شیمیایی و رنگ به صورت JSON",
                        null=True,
                        verbose_name="فرمول رنگ",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="color_shades/%Y/%m/",
                        verbose_name="تصویر نمونه",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="تأیید شده"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تأیید"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_shades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تأیید توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "شید رنگی",
                "verbose_name_plural": "شیدهای رنگی",
                "db_table": "orders_colorshade",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام مشتری")),
                (
                    "company",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="شرکت"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="تلفن"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="موبایل"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="ایمیل"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="آدرس"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="شهر"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="استان"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="شناسه مالیاتی",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="سقف اعتبار (ریال)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
            ],
            options={
                "verbose_name": "مشتری",
                "verbose_name_plural": "مشتریان",
                "db_table": "orders_customer",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="فرمت: ORD-YYYYMMDD-NNN",
                        max_length=20,
                        unique=True,
                        verbose_name="شماره سفارش",
                    ),
                ),
                (
                    "yarn_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="نوع نخ"
                    ),
                ),
                (
                    "yarn_count",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: Ne 30/1",
                        max_length=50,
                        verbose_name="نمره نخ",
                    ),
                ),
                (
                    "quantity_kg",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="مقدار (kg)"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="قیمت واحد (ریال)",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=18,
                        null=True,
                        verbose_name="مبلغ کل (ریال)",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تحویل"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "کم"),
                            ("normal", "عادی"),
                            ("high", "بالا"),
                            ("urgent", "فوری"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("confirmed", "تأیید شده"),
                            ("in_production", "در حال تولید"),
                            ("quality_check", "کنترل کیفیت"),
                            ("ready", "آماده تحویل"),
                            ("delivered", "تحویل داده شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "progress_pct",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="۰ تا ۱۰۰", verbose_name="پیشرفت (%)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "color_shade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="orders.colorshade",
                        verbose_name="شید رنگی",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد توسط",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="orders.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
                "db_table": "orders_order",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["customer"], name="idx_order_customer"),
                    models.Index(fields=["status"], name="idx_order_status"),
                    models.Index(fields=["delivery_date"], name="idx_order_delivery"),
                    models.Index(
                        fields=["priority", "status"], name="idx_order_prio_status"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ColorApprovalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "ارسال شده"),
                            ("customer_review", "در بررسی مشتری"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("revised", "اصلاح شده"),
                        ],
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "sample_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="color_samples/%Y/%m/",
                        verbose_name="تصویر نمونه ارسالی",
                    ),
                ),
                (
                    "customer_feedback",
                    models.TextField(
                        blank=True, default="", verbose_name="بازخورد مشتری"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "color_shade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_history",
                        to="orders.colorshade",
                        verbose_name="شید رنگی",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_approvals",
                        to="orders.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="color_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بررسی توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخچه تأیید رنگ",
                "verbose_name_plural": "تاریخچه تأیید رنگ",
                "db_table": "orders_colorapprovalhistory",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["color_shade", "status"], name="idx_shade_status"
                    )
                ],
            },
        ),
    ]
