# Generated by Django 4.2.21 on 2026-02-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_shift_code_productionline_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="production_line",
            field=models.ForeignKey(
                blank=True,
                help_text="خطی که این سفارش روی آن تولید می\u200cشود",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="core.productionline",
                verbose_name="خط تولید",
            ),
        ),
    ]
