# Generated by Django 4.2.21 on 2026-02-16 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("passage", "0001_initial"),
        ("finisher", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="passage_production",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finisher_productions",
                to="passage.production",
                verbose_name="بچ پاساژ",
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="core.shift",
                verbose_name="شیفت",
            ),
        ),
        migrations.AddIndex(
            model_name="production",
            index=models.Index(fields=["production_date"], name="idx_fn_date"),
        ),
    ]
