# Generated by Django 4.2.21 on 2026-02-16 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_shift_code_productionline_and_more"),
        ("finisher", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="production_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="core.productionline",
                verbose_name="خط تولید",
            ),
        ),
    ]
