# Generated by Django 5.1.5 on 2026-02-15 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "کاربری با این نام قبلاً ثبت شده است."
                        },
                        help_text="نام کاربری برای ورود به سیستم",
                        max_length=150,
                        unique=True,
                        verbose_name="نام کاربری",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "national_code",
                    models.CharField(
                        blank=True,
                        help_text="کد ملی ۱۰ رقمی",
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="تلفن"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="ایمیل"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "مدیر سیستم"),
                            ("manager", "مدیر تولید"),
                            ("supervisor", "سرپرست"),
                            ("operator", "اپراتور"),
                            ("viewer", "ناظر"),
                        ],
                        db_index=True,
                        default="operator",
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("production", "تولید"),
                            ("warehouse", "انبار"),
                            ("dyeing", "رنگرزی"),
                            ("maintenance", "نگهداری و تعمیرات"),
                            ("quality", "کنترل کیفیت"),
                            ("office", "اداری"),
                        ],
                        db_index=True,
                        default="production",
                        max_length=20,
                        verbose_name="بخش",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="دسترسی پنل مدیریت"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ عضویت"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین ورود"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "db_table": "accounts_user",
                "ordering": ["-date_joined"],
                "indexes": [
                    models.Index(fields=["role"], name="idx_user_role"),
                    models.Index(fields=["department"], name="idx_user_dept"),
                    models.Index(fields=["is_active"], name="idx_user_active"),
                ],
            },
        ),
    ]
