# Generated by Django 4.2.21 on 2026-02-16 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blowroom", "0001_initial"),
        ("orders", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شماره بچ"
                    ),
                ),
                ("production_date", models.DateField(verbose_name="تاریخ تولید")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "در حال تولید"),
                            ("completed", "تکمیل شده"),
                            ("quality_hold", "توقف کیفی"),
                            ("cancelled", "لغو شده"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="شروع"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="داده\u200cهای سنسوری و تحلیلی",
                        null=True,
                        verbose_name="متادیتا (AI)",
                    ),
                ),
                (
                    "speed_rpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="سرعت (RPM)",
                    ),
                ),
                (
                    "sliver_count",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="نمره (ضخامت) فتیله خروجی",
                        max_digits=8,
                        verbose_name="نمره فتیله",
                    ),
                ),
                (
                    "sliver_weight_gperm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="وزن فتیله (g/m)",
                    ),
                ),
                (
                    "input_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="وزن ورودی (kg)",
                    ),
                ),
                (
                    "output_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="وزن خروجی (kg)",
                    ),
                ),
                (
                    "waste_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="ضایعات (kg)",
                    ),
                ),
                (
                    "waste_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="درصد ضایعات",
                    ),
                ),
                (
                    "cleaning_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="زمان تمیزکاری"
                    ),
                ),
                (
                    "last_cleaning_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین تمیزکاری"
                    ),
                ),
                (
                    "neps_count",
                    models.IntegerField(
                        blank=True,
                        help_text="شاخص کیفیت - مقدار کمتر بهتر (برای AI)",
                        null=True,
                        verbose_name="تعداد گره (Neps)",
                    ),
                ),
                (
                    "blowroom_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carding_productions",
                        to="blowroom.batch",
                        verbose_name="بچ حلاجی",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.machine",
                        verbose_name="ماشین",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اپراتور",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.shift",
                        verbose_name="شیفت",
                    ),
                ),
            ],
            options={
                "verbose_name": "تولید کاردینگ",
                "verbose_name_plural": "تولیدات کاردینگ",
                "db_table": "carding_production",
                "indexes": [
                    models.Index(fields=["production_date"], name="idx_cd_date"),
                    models.Index(fields=["machine"], name="idx_cd_machine"),
                ],
            },
        ),
    ]
