# Generated by Django 4.2.21 on 2026-02-16 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finisher", "0002_initial"),
        ("orders", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelerReplacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("replaced_at", models.DateTimeField(verbose_name="تاریخ تعویض")),
                (
                    "old_traveler",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="شیطانک قدیم",
                    ),
                ),
                (
                    "new_traveler",
                    models.CharField(max_length=50, verbose_name="شیطانک جدید"),
                ),
                (
                    "spindle_range",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: 1-240",
                        max_length=50,
                        verbose_name="بازه دوک\u200cها",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("scheduled", "برنامه\u200cریزی شده"),
                            ("worn", "فرسوده"),
                            ("breakage", "شکستگی"),
                            ("quality", "مشکل کیفی"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="دلیل تعویض",
                    ),
                ),
                (
                    "running_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="ساعت کارکرد تا تعویض",
                    ),
                ),
                (
                    "next_due_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="برای هشدار PM",
                        null=True,
                        verbose_name="تعویض بعدی",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traveler_replacements",
                        to="core.machine",
                        verbose_name="ماشین",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traveler_replacements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اپراتور",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعویض شیطانک",
                "verbose_name_plural": "تعویض شیطانک\u200cها",
                "db_table": "spinning_travelerreplacement",
                "ordering": ["-replaced_at"],
                "indexes": [
                    models.Index(fields=["machine"], name="idx_tr_machine"),
                    models.Index(fields=["next_due_at"], name="idx_tr_next_due"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شماره بچ"
                    ),
                ),
                ("production_date", models.DateField(verbose_name="تاریخ تولید")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "در حال تولید"),
                            ("completed", "تکمیل شده"),
                            ("quality_hold", "توقف کیفی"),
                            ("cancelled", "لغو شده"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="شروع"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="داده\u200cهای سنسوری و تحلیلی",
                        null=True,
                        verbose_name="متادیتا (AI)",
                    ),
                ),
                (
                    "spindle_speed_rpm",
                    models.IntegerField(verbose_name="سرعت دوک (RPM)"),
                ),
                (
                    "twist_tpm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="دور بر متر - تعیین\u200cکننده استحکام نخ",
                        max_digits=8,
                        verbose_name="تاب (TPM)",
                    ),
                ),
                (
                    "twist_direction",
                    models.CharField(
                        choices=[("S", "S (چپ\u200cتاب)"), ("Z", "Z (راست\u200cتاب)")],
                        default="Z",
                        max_length=1,
                        verbose_name="جهت تاب",
                    ),
                ),
                (
                    "yarn_count",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="نمره نخ نهایی"
                    ),
                ),
                (
                    "traveler_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="شماره شیطانک",
                    ),
                ),
                (
                    "traveler_type",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="نوع شیطانک"
                    ),
                ),
                (
                    "ring_diameter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="قطر رینگ (mm)",
                    ),
                ),
                (
                    "input_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="وزن ورودی (kg)",
                    ),
                ),
                (
                    "output_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="وزن خروجی (kg)",
                    ),
                ),
                (
                    "num_spindles_active",
                    models.IntegerField(blank=True, null=True, verbose_name="دوک فعال"),
                ),
                (
                    "num_spindles_total",
                    models.IntegerField(blank=True, null=True, verbose_name="دوک کل"),
                ),
                (
                    "breakage_count",
                    models.IntegerField(
                        default=0,
                        help_text="شاخص کیفیت - الگوی پارگی برای AI",
                        verbose_name="تعداد پارگی",
                    ),
                ),
                (
                    "efficiency_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="OEE - شاخص عملکرد برای AI",
                        max_digits=5,
                        null=True,
                        verbose_name="راندمان (%)",
                    ),
                ),
                (
                    "finisher_production",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spinning_productions",
                        to="finisher.production",
                        verbose_name="بچ فینیشر",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.machine",
                        verbose_name="ماشین",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اپراتور",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.shift",
                        verbose_name="شیفت",
                    ),
                ),
            ],
            options={
                "verbose_name": "تولید رینگ",
                "verbose_name_plural": "تولیدات رینگ",
                "db_table": "spinning_production",
                "indexes": [
                    models.Index(fields=["production_date"], name="idx_sp_date"),
                    models.Index(fields=["machine"], name="idx_sp_machine"),
                ],
            },
        ),
    ]
