# Generated by Django 5.1.5 on 2026-02-15 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثال: صبح، عصر، شب",
                        max_length=50,
                        verbose_name="نام شیفت",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="مثال: A, B, C",
                        max_length=5,
                        unique=True,
                        verbose_name="کد شیفت",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="ساعت شروع")),
                ("end_time", models.TimeField(verbose_name="ساعت پایان")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "شیفت",
                "verbose_name_plural": "شیفت\u200cها",
                "db_table": "core_shift",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="مثال: CR-01, RG-15, BL-02",
                        max_length=20,
                        unique=True,
                        verbose_name="کد ماشین",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثال: کارد شماره ۱، رینگ سالن ب",
                        max_length=100,
                        verbose_name="نام ماشین",
                    ),
                ),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("blowroom", "حلاجی"),
                            ("carding", "کاردینگ"),
                            ("passage", "پاساژ / کشش"),
                            ("finisher", "فینیشر"),
                            ("ring", "رینگ"),
                            ("dyeing", "دستگاه رنگرزی"),
                            ("boiler", "دیگ بخار"),
                            ("dryer", "خشک\u200cکن"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="نوع ماشین",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("inactive", "غیرفعال"),
                            ("maintenance", "در حال تعمیر"),
                            ("decommissioned", "از رده خارج"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="سازنده"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="مدل"
                    ),
                ),
                (
                    "year_installed",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="سال نصب"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: سالن الف، طبقه ۲",
                        max_length=100,
                        verbose_name="محل استقرار",
                    ),
                ),
                (
                    "specs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="مشخصات فنی ماشین به صورت JSON (برای تحلیل AI)",
                        null=True,
                        verbose_name="مشخصات فنی",
                    ),
                ),
            ],
            options={
                "verbose_name": "ماشین",
                "verbose_name_plural": "ماشین\u200cآلات",
                "db_table": "core_machine",
                "ordering": ["machine_type", "code"],
                "indexes": [
                    models.Index(
                        fields=["machine_type", "status"],
                        name="idx_machine_type_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "ایجاد"),
                            ("update", "ویرایش"),
                            ("delete", "حذف"),
                        ],
                        max_length=10,
                        verbose_name="عملیات",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(max_length=100, verbose_name="نام جدول"),
                ),
                ("record_id", models.BigIntegerField(verbose_name="شناسه رکورد")),
                (
                    "old_values",
                    models.JSONField(blank=True, null=True, verbose_name="مقادیر قبلی"),
                ),
                (
                    "new_values",
                    models.JSONField(blank=True, null=True, verbose_name="مقادیر جدید"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ تغییرات",
                "verbose_name_plural": "لاگ تغییرات",
                "db_table": "core_auditlog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["table_name", "record_id"],
                        name="idx_audit_table_record",
                    ),
                    models.Index(fields=["user"], name="idx_audit_user"),
                    models.Index(fields=["-created_at"], name="idx_audit_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("info", "اطلاعات"),
                            ("warning", "هشدار"),
                            ("danger", "خطر"),
                            ("success", "موفقیت"),
                            ("maintenance", "نگهداری"),
                        ],
                        default="info",
                        max_length=15,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="لینک"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="گیرنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "db_table": "core_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"], name="idx_notif_recipient_read"
                    ),
                    models.Index(fields=["-created_at"], name="idx_notif_created"),
                ],
            },
        ),
    ]
