# Generated by Django 4.2.21 on 2026-02-16 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="code",
            field=models.CharField(
                help_text="مثال: L1-A, L1-B, L2-A",
                max_length=20,
                unique=True,
                verbose_name="کد شیفت",
            ),
        ),
        migrations.CreateModel(
            name="ProductionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="مثال: LINE-01, LINE-02",
                        max_length=20,
                        unique=True,
                        verbose_name="کد خط",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثال: خط یک - نخ پنبه\u200cای",
                        max_length=100,
                        verbose_name="نام خط تولید",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("inactive", "غیرفعال"),
                            ("maintenance", "در حال تعمیر"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: نخ پنبه Ne30، نخ مخلوط PES/VIS",
                        max_length=100,
                        verbose_name="نوع محصول",
                    ),
                ),
                (
                    "target_capacity_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="ظرفیت هدف (کیلو/شیفت)",
                    ),
                ),
                (
                    "specs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="ظرفیت، سرعت، محدودیت\u200cها (JSON)",
                        null=True,
                        verbose_name="مشخصات خط",
                    ),
                ),
                (
                    "line_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_lines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مدیر خط",
                    ),
                ),
            ],
            options={
                "verbose_name": "خط تولید",
                "verbose_name_plural": "خطوط تولید",
                "db_table": "core_production_line",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="machine",
            name="production_line",
            field=models.ForeignKey(
                blank=True,
                help_text="خط تولیدی که این ماشین به آن اختصاص دارد",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machines",
                to="core.productionline",
                verbose_name="خط تولید",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="production_line",
            field=models.ForeignKey(
                blank=True,
                help_text="خالی = شیفت عمومی برای همه خطوط",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="core.productionline",
                verbose_name="خط تولید",
            ),
        ),
        migrations.CreateModel(
            name="LineShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "production_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to="core.productionline",
                        verbose_name="خط تولید",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_assignments",
                        to="core.shift",
                        verbose_name="شیفت",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_supervisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سرشیفت",
                    ),
                ),
            ],
            options={
                "verbose_name": "اختصاص سرشیفت",
                "verbose_name_plural": "اختصاص\u200cهای سرشیفت",
                "db_table": "core_line_shift_assignment",
                "unique_together": {("production_line", "shift")},
            },
        ),
    ]
