# Generated by Django 4.2.21 on 2026-02-16 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
        ("orders", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شماره بچ"
                    ),
                ),
                ("production_date", models.DateField(verbose_name="تاریخ تولید")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "در حال تولید"),
                            ("completed", "تکمیل شده"),
                            ("quality_hold", "توقف کیفی"),
                            ("cancelled", "لغو شده"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="شروع"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="داده\u200cهای سنسوری و تحلیلی",
                        null=True,
                        verbose_name="متادیتا (AI)",
                    ),
                ),
                (
                    "total_input_weight",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="وزن کل ورودی (kg)",
                    ),
                ),
                (
                    "output_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="وزن خروجی (kg)",
                    ),
                ),
                (
                    "waste_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="وزن ضایعات (kg)",
                    ),
                ),
                (
                    "waste_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="درصد ضایعات",
                    ),
                ),
                (
                    "blend_recipe",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='نسبت الیاف: {"PES": 70, "VIS": 30}',
                        null=True,
                        verbose_name="فرمول مخلوط",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.machine",
                        verbose_name="ماشین",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اپراتور",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.shift",
                        verbose_name="شیفت",
                    ),
                ),
            ],
            options={
                "verbose_name": "بچ حلاجی",
                "verbose_name_plural": "بچ\u200cهای حلاجی",
                "db_table": "blowroom_batch",
            },
        ),
        migrations.CreateModel(
            name="BatchInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_used",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="وزن مصرفی (kg)"
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="درصد در مخلوط",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="blowroom.batch",
                        verbose_name="بچ",
                    ),
                ),
                (
                    "fiber_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blowroom_usages",
                        to="inventory.fiberstock",
                        verbose_name="الیاف انبار",
                    ),
                ),
            ],
            options={
                "verbose_name": "ورودی بچ حلاجی",
                "verbose_name_plural": "ورودی\u200cهای بچ حلاجی",
                "db_table": "blowroom_batchinput",
            },
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["production_date"], name="idx_bl_date"),
        ),
    ]
