# Generated by Django 4.2.21 on 2026-02-16 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شماره بچ"
                    ),
                ),
                ("production_date", models.DateField(verbose_name="تاریخ تولید")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "در حال تولید"),
                            ("completed", "تکمیل شده"),
                            ("quality_hold", "توقف کیفی"),
                            ("cancelled", "لغو شده"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="شروع"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="داده\u200cهای سنسوری و تحلیلی",
                        null=True,
                        verbose_name="متادیتا (AI)",
                    ),
                ),
                (
                    "passage_number",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "پاساژ اول"), (2, "پاساژ دوم")],
                        default=1,
                        help_text="۱=اول (ورودی از کاردینگ) | ۲=دوم (ورودی از پاساژ اول)",
                        verbose_name="شماره پاساژ",
                    ),
                ),
                (
                    "num_inputs",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="معمولاً ۶ تا ۸ فتیله",
                        verbose_name="تعداد فتیله ورودی",
                    ),
                ),
                (
                    "draft_ratio",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="مثلاً 6.500 یعنی ۶.۵ برابر",
                        max_digits=8,
                        verbose_name="نسبت کشش",
                    ),
                ),
                (
                    "output_sliver_count",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="نمره فتیله خروجی"
                    ),
                ),
                (
                    "output_weight_gperm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="وزن فتیله خروجی (g/m)",
                    ),
                ),
                (
                    "input_total_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="وزن کل ورودی (kg)",
                    ),
                ),
                (
                    "output_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="وزن خروجی (kg)",
                    ),
                ),
                (
                    "speed_mpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="سرعت (m/min)",
                    ),
                ),
                (
                    "evenness_cv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ضریب تغییرات - مقدار کمتر بهتر (شاخص AI)",
                        max_digits=5,
                        null=True,
                        verbose_name="CV% یکنواختی",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.machine",
                        verbose_name="ماشین",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اپراتور",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.shift",
                        verbose_name="شیفت",
                    ),
                ),
            ],
            options={
                "verbose_name": "تولید پاساژ",
                "verbose_name_plural": "تولیدات پاساژ",
                "db_table": "passage_production",
            },
        ),
        migrations.CreateModel(
            name="Input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_position",
                    models.PositiveSmallIntegerField(
                        help_text="شماره ۱ تا ۸", verbose_name="جایگاه ورودی"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("carding", "کاردینگ"), ("passage", "پاساژ قبلی")],
                        max_length=10,
                        verbose_name="نوع منبع",
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        help_text="ID بچ کاردینگ یا پاساژ", verbose_name="شناسه منبع"
                    ),
                ),
                (
                    "source_batch_number",
                    models.CharField(
                        help_text="برای خوانایی سریع بدون JOIN",
                        max_length=50,
                        verbose_name="شماره بچ منبع",
                    ),
                ),
                (
                    "weight_used",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="وزن مصرفی (kg)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "passage_production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="passage.production",
                        verbose_name="بچ پاساژ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ورودی پاساژ",
                "verbose_name_plural": "ورودی\u200cهای پاساژ",
                "db_table": "passage_input",
            },
        ),
        migrations.AddIndex(
            model_name="production",
            index=models.Index(fields=["production_date"], name="idx_ps_date"),
        ),
        migrations.AddIndex(
            model_name="production",
            index=models.Index(fields=["passage_number"], name="idx_ps_number"),
        ),
        migrations.AddIndex(
            model_name="input",
            index=models.Index(
                fields=["source_type", "source_id"], name="idx_pi_source"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="input",
            unique_together={("passage_production", "input_position")},
        ),
    ]
