# Generated by Django 4.2.21 on 2026-02-16 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("core", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="شماره بچ"
                    ),
                ),
                ("production_date", models.DateField(verbose_name="تاریخ تولید")),
                (
                    "fiber_weight",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="وزن الیاف (kg)"
                    ),
                ),
                (
                    "liquor_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="مثلاً 1:8",
                        max_digits=5,
                        null=True,
                        verbose_name="نسبت حمام",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="دمای حمام (°C)",
                    ),
                ),
                (
                    "duration_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مدت زمان (دقیقه)"
                    ),
                ),
                (
                    "ph_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="pH",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparation", "آماده\u200cسازی"),
                            ("in_progress", "در حال رنگرزی"),
                            ("cooling", "خنک\u200cسازی"),
                            ("drying", "خشک\u200cکردن"),
                            ("completed", "تکمیل شده"),
                            ("failed", "ناموفق"),
                        ],
                        db_index=True,
                        default="preparation",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="شروع"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "quality_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "قبول"),
                            ("fail", "مردود"),
                            ("conditional", "مشروط"),
                        ],
                        default="",
                        max_length=15,
                        verbose_name="نتیجه کیفیت",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="متادیتا (AI)"
                    ),
                ),
                (
                    "color_shade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dyeing_batches",
                        to="orders.colorshade",
                        verbose_name="شید رنگی",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dyeing_batches",
                        to="core.machine",
                        verbose_name="دیگ رنگرزی",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dyeing_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اپراتور",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dyeing_batches",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dyeing_batches",
                        to="core.shift",
                        verbose_name="شیفت",
                    ),
                ),
            ],
            options={
                "verbose_name": "بچ رنگرزی",
                "verbose_name_plural": "بچ\u200cهای رنگرزی",
                "db_table": "dyeing_batch",
                "ordering": ["-production_date"],
            },
        ),
        migrations.CreateModel(
            name="ChemicalUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[("dye", "رنگ"), ("chemical", "ماده شیمیایی")],
                        max_length=10,
                        verbose_name="نوع ماده",
                    ),
                ),
                (
                    "quantity_used",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="مقدار مصرفی"
                    ),
                ),
                ("unit", models.CharField(max_length=10, verbose_name="واحد")),
                (
                    "step_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: شست\u200cوشو، رنگرزی، تثبیت",
                        max_length=100,
                        verbose_name="مرحله مصرف",
                    ),
                ),
                (
                    "sequence_order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ترتیب اضافه\u200cکردن"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "chemical_stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dyeing_usages",
                        to="inventory.chemicalstock",
                        verbose_name="ماده شیمیایی مصرفی",
                    ),
                ),
                (
                    "dye_stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dyeing_usages",
                        to="inventory.dyestock",
                        verbose_name="رنگ مصرفی",
                    ),
                ),
                (
                    "dyeing_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemical_usages",
                        to="dyeing.batch",
                        verbose_name="بچ رنگرزی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مصرف مواد رنگرزی",
                "verbose_name_plural": "مصرف مواد رنگرزی",
                "db_table": "dyeing_chemicalusage",
                "ordering": ["sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="DryerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField(verbose_name="تاریخ")),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="دما (°C)",
                    ),
                ),
                (
                    "duration_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مدت (دقیقه)"
                    ),
                ),
                (
                    "humidity_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="رطوبت خروجی (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "در حال کار"),
                            ("idle", "خاموش"),
                            ("maintenance", "در حال تعمیر"),
                        ],
                        default="running",
                        max_length=15,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="متادیتا (AI)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "dyeing_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dryer_logs",
                        to="dyeing.batch",
                        verbose_name="بچ رنگرزی",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dryer_logs",
                        to="core.machine",
                        verbose_name="خشک\u200cکن",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dryer_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اپراتور",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dryer_logs",
                        to="core.shift",
                        verbose_name="شیفت",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ خشک\u200cکن",
                "verbose_name_plural": "لاگ\u200cهای خشک\u200cکن",
                "db_table": "dyeing_dryerlog",
                "ordering": ["-log_date"],
                "indexes": [
                    models.Index(
                        fields=["machine", "log_date"], name="idx_dryer_machine_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BoilerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField(verbose_name="تاریخ")),
                (
                    "pressure_bar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="فشار (bar)",
                    ),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="دما (°C)",
                    ),
                ),
                (
                    "water_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="سطح آب (%)",
                    ),
                ),
                (
                    "fuel_consumed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="مصرف سوخت",
                    ),
                ),
                (
                    "running_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="ساعت کار",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "در حال کار"),
                            ("idle", "خاموش"),
                            ("maintenance", "در حال تعمیر"),
                        ],
                        default="running",
                        max_length=15,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="متادیتا (AI)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boiler_logs",
                        to="core.machine",
                        verbose_name="دیگ بخار",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boiler_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اپراتور",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boiler_logs",
                        to="core.shift",
                        verbose_name="شیفت",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ دیگ بخار",
                "verbose_name_plural": "لاگ\u200cهای دیگ بخار",
                "db_table": "dyeing_boilerlog",
                "ordering": ["-log_date"],
                "indexes": [
                    models.Index(
                        fields=["machine", "log_date"], name="idx_boiler_machine_date"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["production_date"], name="idx_dy_date"),
        ),
    ]
