# Generated by Django 4.2.21 on 2026-02-15 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiberCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثال: پلی\u200cاستر، اکریلیک، پشم",
                        max_length=100,
                        verbose_name="نام دسته",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="مثال: PES, ACR, WOL",
                        max_length=20,
                        unique=True,
                        verbose_name="کد",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "دسته\u200cبندی الیاف",
                "verbose_name_plural": "دسته\u200cبندی الیاف",
                "db_table": "inventory_fibercategory",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DyeStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام رنگ")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="کد رنگ"),
                ),
                (
                    "color_family",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: قرمز، آبی، سبز",
                        max_length=50,
                        verbose_name="خانواده رنگ",
                    ),
                ),
                (
                    "dye_type",
                    models.CharField(
                        choices=[
                            ("reactive", "راکتیو"),
                            ("disperse", "دیسپرس"),
                            ("acid", "اسیدی"),
                            ("vat", "خمی"),
                            ("direct", "مستقیم"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="نوع رنگ",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="سازنده"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(max_length=50, verbose_name="شماره بچ"),
                ),
                (
                    "initial_weight",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="مقدار اولیه"
                    ),
                ),
                (
                    "current_weight",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="مقدار فعلی"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "کیلوگرم"), ("g", "گرم"), ("liter", "لیتر")],
                        default="kg",
                        max_length=10,
                        verbose_name="واحد",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="قیمت واحد (ریال)",
                    ),
                ),
                ("received_date", models.DateField(verbose_name="تاریخ ورود")),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ انقضا"),
                ),
                (
                    "storage_temp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="دمای نگهداری (°C)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "موجود"),
                            ("reserved", "رزرو شده"),
                            ("consumed", "مصرف شده"),
                            ("expired", "منقضی"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
            ],
            options={
                "verbose_name": "موجودی رنگ",
                "verbose_name_plural": "موجودی رنگ",
                "db_table": "inventory_dyestock",
                "ordering": ["received_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "received_date"], name="idx_dye_status_date"
                    ),
                    models.Index(fields=["dye_type"], name="idx_dye_type"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChemicalStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام ماده")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="کد"),
                ),
                (
                    "chemical_type",
                    models.CharField(
                        choices=[
                            ("acid", "اسید"),
                            ("alkali", "قلیا"),
                            ("salt", "نمک"),
                            ("softener", "نرم\u200cکننده"),
                            ("fixative", "تثبیت\u200cکننده"),
                            ("auxiliary", "کمکی"),
                            ("other", "سایر"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="نوع ماده",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="سازنده"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(max_length=50, verbose_name="شماره بچ"),
                ),
                (
                    "initial_amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="مقدار اولیه"
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="مقدار فعلی"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "کیلوگرم"),
                            ("g", "گرم"),
                            ("liter", "لیتر"),
                            ("ml", "میلی\u200cلیتر"),
                        ],
                        default="kg",
                        max_length=10,
                        verbose_name="واحد",
                    ),
                ),
                (
                    "concentration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="غلظت (%)",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="قیمت واحد (ریال)",
                    ),
                ),
                ("received_date", models.DateField(verbose_name="تاریخ ورود")),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ انقضا"),
                ),
                (
                    "msds_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="msds/%Y/%m/",
                        verbose_name="برگه ایمنی (MSDS)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "موجود"),
                            ("reserved", "رزرو شده"),
                            ("consumed", "مصرف شده"),
                            ("expired", "منقضی"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
            ],
            options={
                "verbose_name": "موجودی مواد شیمیایی",
                "verbose_name_plural": "موجودی مواد شیمیایی",
                "db_table": "inventory_chemicalstock",
                "ordering": ["received_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "received_date"], name="idx_chem_status_date"
                    ),
                    models.Index(fields=["chemical_type"], name="idx_chemical_type"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_type",
                    models.CharField(
                        choices=[
                            ("fiber", "الیاف"),
                            ("dye", "رنگ"),
                            ("chemical", "مواد شیمیایی"),
                        ],
                        max_length=20,
                        verbose_name="نوع موجودی",
                    ),
                ),
                ("stock_id", models.BigIntegerField(verbose_name="شناسه موجودی")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("receive", "ورود به انبار"),
                            ("issue", "خروج از انبار"),
                            ("return", "برگشت به انبار"),
                            ("adjust", "تعدیل موجودی"),
                            ("waste", "ضایعات"),
                        ],
                        max_length=20,
                        verbose_name="نوع تراکنش",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="مقدار"
                    ),
                ),
                ("unit", models.CharField(max_length=10, verbose_name="واحد")),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: blowroom_batch, dyeing_batch",
                        max_length=50,
                        verbose_name="نوع مرجع",
                    ),
                ),
                (
                    "reference_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="شناسه مرجع"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ تراکنش"
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش انبار",
                "verbose_name_plural": "تراکنش\u200cهای انبار",
                "db_table": "inventory_stocktransaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stock_type", "stock_id"], name="idx_stock_ref"
                    ),
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="idx_txn_reference",
                    ),
                    models.Index(fields=["-created_at"], name="idx_txn_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FiberStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="شماره بچ/لات منحصربفرد",
                        max_length=50,
                        unique=True,
                        verbose_name="شماره بچ",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="شماره لات تأمین\u200cکننده",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="تأمین\u200cکننده",
                    ),
                ),
                (
                    "color_raw",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="رنگ الیاف خام (سفید، اکرو و ...)",
                        max_length=100,
                        verbose_name="رنگ اولیه",
                    ),
                ),
                (
                    "denier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ضخامت الیاف (دنیر)",
                        max_digits=8,
                        null=True,
                        verbose_name="دنیر",
                    ),
                ),
                (
                    "staple_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="طول الیاف (mm)",
                    ),
                ),
                (
                    "initial_weight",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="وزن اولیه (kg)"
                    ),
                ),
                (
                    "current_weight",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="وزن فعلی (kg)"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="قیمت واحد (ریال)",
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        help_text="کلید FIFO: اول وارد، اول مصرف",
                        verbose_name="تاریخ ورود",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ انقضا"),
                ),
                (
                    "warehouse_loc",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: ردیف ۳ - قفسه ب",
                        max_length=50,
                        verbose_name="محل انبار",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "موجود"),
                            ("reserved", "رزرو شده"),
                            ("consumed", "مصرف شده"),
                            ("returned", "برگشتی"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "quality_grade",
                    models.CharField(
                        choices=[("A", "درجه یک"), ("B", "درجه دو"), ("C", "درجه سه")],
                        default="A",
                        max_length=1,
                        verbose_name="درجه کیفیت",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks",
                        to="inventory.fibercategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "موجودی الیاف",
                "verbose_name_plural": "موجودی الیاف",
                "db_table": "inventory_fiberstock",
                "ordering": ["received_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "received_date"], name="idx_fiber_fifo"
                    ),
                    models.Index(fields=["category"], name="idx_fiber_category"),
                ],
            },
        ),
    ]
