# Generated by Django 4.2.21 on 2026-02-16 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("preventive", "پیشگیرانه"),
                            ("corrective", "اصلاحی"),
                            ("predictive", "پیش\u200cبینانه"),
                            ("overhaul", "اساسی"),
                        ],
                        max_length=15,
                        verbose_name="نوع نگهداری",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="شرح"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "روزانه"),
                            ("weekly", "هفتگی"),
                            ("biweekly", "دو هفته\u200cای"),
                            ("monthly", "ماهانه"),
                            ("quarterly", "سه\u200cماهه"),
                            ("semi_annual", "شش\u200cماهه"),
                            ("annual", "سالانه"),
                            ("custom", "سفارشی"),
                        ],
                        max_length=15,
                        verbose_name="دوره تکرار",
                    ),
                ),
                (
                    "custom_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="تعداد روز (سفارشی)"
                    ),
                ),
                (
                    "last_done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین انجام"
                    ),
                ),
                ("next_due_at", models.DateTimeField(verbose_name="موعد بعدی")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "کم"),
                            ("medium", "متوسط"),
                            ("high", "بالا"),
                            ("critical", "بحرانی"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="اولویت",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مسئول",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_schedules",
                        to="core.machine",
                        verbose_name="ماشین",
                    ),
                ),
            ],
            options={
                "verbose_name": "برنامه سرویس",
                "verbose_name_plural": "برنامه\u200cهای سرویس",
                "db_table": "maintenance_schedule",
                "ordering": ["next_due_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "wo_number",
                    models.CharField(
                        help_text="فرمت: WO-YYYYMMDD-NNN",
                        max_length=20,
                        unique=True,
                        verbose_name="شماره دستور کار",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="شرح"),
                ),
                (
                    "wo_type",
                    models.CharField(
                        choices=[
                            ("preventive", "پیشگیرانه"),
                            ("corrective", "اصلاحی"),
                            ("emergency", "اضطراری"),
                        ],
                        max_length=15,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "کم"),
                            ("medium", "متوسط"),
                            ("high", "بالا"),
                            ("critical", "بحرانی"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("in_progress", "در حال انجام"),
                            ("waiting_parts", "در انتظار قطعات"),
                            ("completed", "تکمیل شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="شروع"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "downtime_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مدت توقف (دقیقه)"
                    ),
                ),
                (
                    "cost_parts",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="هزینه قطعات (ریال)",
                    ),
                ),
                (
                    "cost_labor",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="هزینه دستمزد (ریال)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_workorders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مسئول اجرا",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="core.machine",
                        verbose_name="ماشین",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_workorders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="گزارش\u200cدهنده",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="maintenance.schedule",
                        verbose_name="برنامه PM",
                    ),
                ),
            ],
            options={
                "verbose_name": "دستور کار",
                "verbose_name_plural": "دستورهای کار",
                "db_table": "maintenance_workorder",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MachineServiceDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(max_length=100, verbose_name="نوع سرویس"),
                ),
                ("service_date", models.DateField(verbose_name="تاریخ سرویس")),
                (
                    "next_service",
                    models.DateField(blank=True, null=True, verbose_name="سرویس بعدی"),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="سرویس\u200cکار",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="هزینه (ریال)",
                    ),
                ),
                (
                    "parts_replaced",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="قطعات تعویض شده",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_dates",
                        to="core.machine",
                        verbose_name="ماشین",
                    ),
                ),
            ],
            options={
                "verbose_name": "سابقه سرویس",
                "verbose_name_plural": "سوابق سرویس",
                "db_table": "maintenance_machineservicedate",
                "ordering": ["-service_date"],
            },
        ),
        migrations.CreateModel(
            name="DowntimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="شروع توقف")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان توقف"
                    ),
                ),
                (
                    "duration_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مدت (دقیقه)"
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("mechanical", "مکانیکی"),
                            ("electrical", "برقی"),
                            ("material", "مواد اولیه"),
                            ("operator", "اپراتور"),
                            ("quality", "کیفیت"),
                            ("planned", "برنامه\u200cریزی شده"),
                            ("other", "سایر"),
                        ],
                        max_length=15,
                        verbose_name="دسته\u200cبندی دلیل",
                    ),
                ),
                (
                    "reason_detail",
                    models.CharField(max_length=500, verbose_name="جزئیات دلیل"),
                ),
                (
                    "production_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="تولید از دست رفته (kg)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="متادیتا (AI)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downtime_logs",
                        to="core.machine",
                        verbose_name="ماشین",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downtime_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اپراتور",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downtime_logs",
                        to="core.shift",
                        verbose_name="شیفت",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downtime_logs",
                        to="maintenance.workorder",
                        verbose_name="دستور کار",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ توقف",
                "verbose_name_plural": "لاگ\u200cهای توقف",
                "db_table": "maintenance_downtimelog",
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["machine"], name="idx_wo_machine"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["priority", "status"], name="idx_wo_prio_status"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["next_due_at"], name="idx_mnt_next_due"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["machine"], name="idx_mnt_machine"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["is_active", "next_due_at"], name="idx_mnt_overdue"
            ),
        ),
        migrations.AddIndex(
            model_name="machineservicedate",
            index=models.Index(
                fields=["machine", "service_date"], name="idx_svc_machine_date"
            ),
        ),
        migrations.AddIndex(
            model_name="machineservicedate",
            index=models.Index(fields=["next_service"], name="idx_svc_next"),
        ),
        migrations.AddIndex(
            model_name="downtimelog",
            index=models.Index(
                fields=["machine", "start_time"], name="idx_dt_machine_date"
            ),
        ),
        migrations.AddIndex(
            model_name="downtimelog",
            index=models.Index(fields=["reason_category"], name="idx_dt_reason"),
        ),
        migrations.AddIndex(
            model_name="downtimelog",
            index=models.Index(fields=["shift", "start_time"], name="idx_dt_shift"),
        ),
    ]
